### ISSUE TITLE
Filtered SNV file is empty

### ISSUE THREAD

**Issue by hongenxu** [Genome-Bioinformatics-RadboudUMC/Chameleolyser#3]
Dear Wouter,

I used HG002 test data, the output file HG002.RawSNVs.txt is 16 Mega bytes. But HG002.Filter1SNVs.txt and HG002.Filter2SNVs.txt only have header lines. 
the command lines are as follows. 

`/usr/bin/perl /public/home/zzumag02/src/Chameleolyser/Chameleolyser.pl --FilterRawVariants --WORKING_DIR=/public/home/zzumag02/Projects/STRC/ --SAMPLE_NAME=HG002 `
or 
/usr/bin/perl /public/home/zzumag02/src/Chameleolyser/Chameleolyser.pl --FilterRawVariants --WORKING_DIR=/public/home/zzumag02/Projects/STRC/ --SAMPLE_NAME=HG002  --OMIM=yes`

Best regards,
Hongen

**Comment by WouterSteyaert** [comment]
Dear Hongen, I spotted a small mistake in the "--OMIM=yes" option, I ll fix tonight or tomorrow. I guess that is the problem, but then you should be able to run the tool without that option. If so, re-run prepareBED. If you have an issue without the "--OMIM=yes" option, could you copy me your screenoutput so I can follow what goes wrong?
Best wishes
Wouter

**Comment by WouterSteyaert** [comment]
Hi Hongen, sorry for the confusion, but there isnt an issue with the code I believe. The only thing is that you should always use '--OMIM=yes' or never, in all of the functions of the script. This was not clear based on the tutorial, I adapted now. Please let me know if you still encounter issues, you can then copy your screenoutput.

**Comment by hongenxu** [comment]
problem solved. thanks.
