### ISSUE TITLE
Benchmark variant not in call bed

### ISSUE THREAD

**Issue by valeandri** [Genome-Bioinformatics-RadboudUMC/Chameleolyser#6]
Hi,

I started testing the tool on HG002 using the "benchmark" variants in the supplementary table Supplementary Data [8](https://www.nature.com/articles/s41467-023-42531-9#MOESM11) of the paper https://doi.org/10.1038/s41467-023-42531-9.

I analysed an internal Illumina HG002 sample that was obtained using Twist Exome Core plus Refseq probes. During the comparison between the callset and the benchamrk calls, I found 5 "true" variants present in both the supplementary and the demo output file HG002.Filter1SNVs.txt, but not in my results:
```
chr16	28414806	28414808	G/A
chr19	50462895	50462898	AGAG/-
chr7	102152474	102152476	C/G
chr7	144062692	144062694	C/G
chr9	84561929	84561931	C/T
```
Trying to find a reason, I saw that the calls are in regions where no read was aligned (see IGV screenshot). How was this call made for the benchmark? Am I missing some steps?

![image](https://github.com/Genome-Bioinformatics-RadboudUMC/Chameleolyser/assets/63858464/f172af1a-5634-4e4f-8c8d-1c1893eaaa67)

Thanks in advance,

Valentina

**Comment by WouterSteyaert** [comment]
Hi Valentina,

Thanks for your interest in our tool. For our study we have used the publicly available .BAM for HG002: WES: https://ftptrace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/AshkenazimTrio/HG002_NA24385_son/
OsloUniversityHospital_Exome/151002_7001448_0359_AC7F6GANXX_Sample_HG002-
EEogPU_v02-KIT-Av5_AGATGTAC_L008.posiSrt.markDup.bam. I assume it is enriched using another capture kit and maybe a different target depth. This is the explanation I would assume if only a small subset of these variants do not match with your output. 

Best wishes,
Wouter

**Comment by valeandri** [comment]
Hi Wouter,

I think this was exactly the case, thanks for looking into this!

I would also like to call CNV variants as well and I saw in the paper that you used Exomedepth. We cannot collect that many baseline samples but we should have something like 100 normal samples.

Can I ask you which steps did you perform to adapt ED to pseudogene calling? Should I open a new thread?

Thanks a lot!!

Valentina

**Comment by WouterSteyaert** [comment]
Hey Valentina,

Thanks for your message! We only called CNVs with ExomeDepth to compare with our own homology-based analysis. So for ED we did not alter default settings. Do you have any specific gene/genes in mind? In that case it would be easier to plot the number of unique reads aligned onto homolog1 versus the unique reads onto homolog2 (this can be done based on the output of the tool). You will see point clouds, and the outliers to that might be caused by rare genetic events. If you want to have detailed instructions, you can drop me a message (wasteyae.steyaert@ugent.be)

Best wishes,
Wouter

**Comment by valeandri** [comment]
Thank you Wouter,

I will test ED on our set of ~10 genes and in case I need some more instructions regarding your method I will send you a message, thanks!

Best wishes,
Valentina
